#!/bin/bash
#$ -N create_env
#$ -l mem=3G
#$ -cwd
#$ -pe default 2
#$ -o $HOME/store/sge-logs
#$ -e $HOME/store/sge-logs


export PATH="$HOME/miniconda/bin:$PATH"

conda create -y --name LearningDimensions python=3 pip
conda install -y -c conda-forge -n LearningDimensions opencv

source activate LearningDimensions
conda install -y -q -c anaconda tensorflow-gpu=1.4
pip install imgaug
source deactivate LearningDimensions

cd $HOME/miniconda/pkgs
rm *.tar.bz2 -f 2> /dev/null

