#!/bin/bash
#$ -N baselines
#$ -l mem=2G
#$ -l h_rt=1:30:00
#$ -cwd
#$ -pe default 2
#$ -l cuda=1
#$ -l cuda_cores=384
#$ -o $HOME/store/sge-logs
#$ -e $HOME/store/sge-logs

export PATH="$HOME/miniconda/bin:$PATH"
rm /tmp/* -R -f 2> /dev/null

source activate tensorflow-CS
echo "starting"
for ((i = 1; i <= $2; i++));
do
	python baselines.py $1
done
echo "done with baselines"
source deactivate tensorflow-CS

rm /tmp/* -R -f 2> /dev/null
