#!/bin/bash
#$ -N skl_reg
#$ -l mem=4G
#$ -l h_rt=2:30:00
#$ -cwd
#$ -pe default 8
#$ -o $HOME/store/sge-logs
#$ -e $HOME/store/sge-logs

export PATH="$HOME/miniconda/bin:$PATH"
rm /tmp/* -R -f 2> /dev/null

source activate tensorflow-CS
echo "starting"
for ((i = 1; i <= $2; i++));
do
	python -u sklearn_regression.py $1
done
echo "done with sklearn regression"
source deactivate tensorflow-CS

rm /tmp/* -R -f 2> /dev/null
