#!/bin/bash
#$ -N stripper
#$ -l mem=4G
#$ -l h_rt=1:00:00
#$ -cwd
#$ -pe default 2
#$ -o $HOME/store/sge-logs
#$ -e $HOME/store/sge-logs

export PATH="$HOME/miniconda/bin:$PATH"
rm /tmp/* -R -f 2> /dev/null

source activate tensorflow-CS
echo "starting"
python strip_features.py features/features/all features/images
echo "done with stripping"
source deactivate tensorflow-CS

rm /tmp/* -R -f 2> /dev/null
