#!/bin/bash
#$ -N noun
#$ -l mem=4G
#$ -l h_rt=1:00:00
#$ -cwd
#$ -pe default 2
#$ -l cuda=1
#$ -l cuda_cores=384
#$ -o $HOME/store/sge-logs
#$ -e $HOME/store/sge-logs

export PATH="$HOME/miniconda/bin:$PATH"
rm /tmp/* -R -f 2> /dev/null

source activate LearningDimensions

python data_augmentation.py
python create_feature_vectors.py
python autoencoder.py
python linear_regression.py

source deactivate LearningDimensions

rm /tmp/* -R -f 2> /dev/null
