#!/bin/bash
#$ -N features
#$ -l mem=6G
#$ -l h_rt=2:00:00
#$ -cwd
#$ -pe default 2
#$ -l cuda=1
#$ -l cuda_cores=384
#$ -o $HOME/store/sge-logs
#$ -e $HOME/store/sge-logs

export PATH="$HOME/miniconda/bin:$PATH"
rm /tmp/* -R -f 2> /dev/null

source activate LearningDimensions
echo "starting"
python create_feature_vectors.py
echo "done creating feature vectors"
source deactivate LearningDimensions

rm /tmp/* -R -f 2> /dev/null
