#!/bin/bash
#$ -N shuffler
#$ -l mem=1G
#$ -l h_rt=1:00:00
#$ -cwd
#$ -pe default 2
#$ -o $HOME/store/sge-logs
#$ -e $HOME/store/sge-logs

export PATH="$HOME/miniconda/bin:$PATH"
rm /tmp/* -R -f 2> /dev/null

source activate tensorflow-CS
echo "starting"
python shuffle_targets.py ../mds/output/4D-vectors.csv features/targets-4d
echo "done with shuffling"
source deactivate tensorflow-CS

rm /tmp/* -R -f 2> /dev/null
