#!/bin/bash
#$ -N augment
#$ -l mem=2G
#$ -l h_rt=1:00:00
#$ -cwd
#$ -pe default 2
#$ -l cuda=1
#$ -l cuda_cores=384
#$ -o $HOME/store/sge-logs
#$ -e $HOME/store/sge-logs

export PATH="$HOME/miniconda/bin:$PATH"
rm /tmp/* -R -f 2> /dev/null

source activate tensorflow-CS
echo "starting"
python data_augmentation.py --mapping_file ../MDS-NOUN-4D-vectors.csv
echo "done augmenting"
source deactivate tensorflow-CS

rm /tmp/* -R -f 2> /dev/null
